[project]
name = "inmoose"
version = "0.2.4"
description = "InMoose: the Integrated Multi Omic Open Source Environment"
readme = "README.md"
authors = [
  {name = "Maximilien Colange", email = "maximilien@epigenelabs.com"},
  {name = "Léa Meunier", email = "lea@epigenelabs.com"},
  {name = "Solène Weill", email = "solene@epigenelabs.com"},
]
classifiers = [
  "Programming Language :: Python :: 3",
  "License :: OSI Approved :: GNU General Public License v3 or later (GPLv3+)",
  "Topic :: Scientific/Engineering :: Bio-Informatics",
]
requires-python = ">=3.9"
dependencies = [
  "anndata",
  "mpmath>=1.1.0",
  "numpy>=1.18.5",
  "pandas",
  "patsy",
  "scipy",
  "seaborn",
  "scikit-learn",
]

[project.urls]
Source = "https://github.com/epigenelabs/inmoose"
Documentation = "https://inmoose.readthedocs.io/en/latest/"

[project.optional-dependencies]
doc = [
  "sphinx",
  "sphinx_rtd_theme",
]

[build-system]
requires = ["setuptools", "numpy", "scipy", "Cython==3.0.0b2", "wheel"]

